## Conclusion:
The higher the score2 in anal_zzkmstats table, the higher win rate

In [4]:
import __init__

#last_dir= 1 :  1
#last_dir= 2 : -1
#last_dir=-1 : -1
#last_dir=-2 :  1
# if(abs(i.last_dir)=2,i.last_dir/2*-1,i.last_dir) * s.dir_predicted

sql = """select g.km_id, s.score1, s.score2, count(g.zzitemid) cnt, s.item_cnt,
sum(if(s.meany*(i.y6-i.y5)>0,1,0)) as result, s.meany as pmeany, avg(i.y6-i.y5) as imeany
from anal_zzkmgroups_predicted_D_5_5 g
left join anal_zzitems_D_5_5 i on g.zzitemid = i.zzitemid
left join (select km_id, meany, score1, score2, item_cnt 
    from anal_zzkmstats_D_5_5 
    where km_setid=1) s on g.km_id = s.km_id
group by km_id
"""
sql = """select km_id, score1, score2, score1*score2 score,pmeany, imeany, item_cnt, cnt, result, result/cnt as rate from (%s) a 
-- where score1 >=0.65 and score2 >= 0.65
where item_cnt >= 500
-- and abs(imeany) >= 0.2
-- and cnt >= 100
-- and score2 >= 0.65
-- having rate >= 0.65
-- having score >= 0.8
-- order by rate desc;
order by score desc, cnt desc
""" % (sql)

import pandas as pd
import numpy as np
from db.mydf import MyDf
mydf = MyDf()
df = mydf.read_sql(sql)
df

,km_id,score1,score2,score,pmeany,imeany,item_cnt,cnt,result,rate
0,pek212202_0000000005,0.7,0.989637,0.692746,0.283802,-0.085082,772,165,59.0,0.3576
1,pek121101_0000000004,0.4,1.000000,0.400000,-0.392714,-0.079117,670,49,34.0,0.6939
2,pek121101_0000000003,0.4,0.984402,0.393761,-0.222985,-0.022493,577,117,76.0,0.6496
3,pek212202_0000000003,0.2,1.000000,0.200000,0.495849,0.051424,756,205,95.0,0.4634
4,pek121021_0000000001,0.2,0.949119,0.189824,-0.252115,0.043707,511,100,50.0,0.5000
5,pek212202_0000000002,0.1,0.995652,0.099565,0.132809,-0.005524,920,151,49.0,0.3245
6,pek121011_0000000003,0.1,0.988095,0.098810,-0.264360,0.151504,504,91,32.0,0.3516
7,pek121101_0000000006,0.1,0.986129,0.098613,-0.121385,-0.033030,793,127,84.0,0.6614
8,pek121021_0000000000,0.1,0.981846,0.098185,-0.272594,0.040050,661,104,52.0,0.5000
9,pek212202_0000000004,0.0,0.998532,0.000000,0.377023,0.123306,681,204,124.0,0.6078
10,pek212202_0000000001,0.0,0.987790,0.000000,0.206435,-0.051275,819,199,77.0,0.3869
11,pek121101_0000000000,0.0,0.990826,0.000000,-0.259356,-0.016002,545,162,97.0,0.5988
12,pek121101_0000000005,0.0,0.982456,0.000000,-0.167935,0.047464,798,107,52.0,0.4860
13,pek121101_0000000002,0.0,0.997257,0.000000,-0.226674,0.191366,729,105,39.0,0.3714
14,pek212202_0000000006,0.0,1.000000,0.000000,0.273213,0.122073,888,17,13.0,0.7647

In [5]:
df.corr()

/tmp/ipykernel_1994/1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,score1,score2,score,pmeany,imeany,item_cnt,cnt,result,rate
score1,1.000000,-0.074263,0.999920,0.014134,-0.576997,-0.130498,-0.010212,-0.084128,-0.047939
score2,-0.074263,1.000000,-0.062799,0.403602,0.102781,0.476685,0.097110,0.073913,0.110581
score,0.999920,-0.062799,1.000000,0.016783,-0.578470,-0.125061,-0.009460,-0.083865,-0.047049
pmeany,0.014134,0.403602,0.016783,1.000000,0.040515,0.575809,0.546547,0.366109,-0.123409
imeany,-0.576997,0.102781,-0.578470,0.040515,1.000000,-0.119970,-0.211551,-0.197009,-0.105701
item_cnt,-0.130498,0.476685,-0.125061,0.575809,-0.119970,1.000000,0.073790,-0.133480,-0.073430
cnt,-0.010212,0.097110,-0.009460,0.546547,-0.211551,0.073790,1.000000,0.837847,-0.425763
result,-0.084128,0.073913,-0.083865,0.366109,-0.197009,-0.133480,0.837847,1.000000,0.080633
rate,-0.047939,0.110581,-0.047049,-0.123409,-0.105701,-0.073430,-0.425763,0.080633,1.000000